# Etape 1.3 : Agregations avancees Spark

---
---

## Imports

In [96]:
import sys
import os
from pathlib import Path
import pandas as pd

---

## Chemin des données

In [97]:
DATA_DIR = (Path.cwd() / ".." / "data").resolve()
OUTPUT_DIR = os.path.join(DATA_DIR, "output")
CONSOMMATION_PARQUET_DIR = os.path.join(OUTPUT_DIR, "consommations_clean")
BATIMENTS_PATH = os.path.join(DATA_DIR, "batiments.csv")
CONSO_AGREGEES_PARKET = os.path.join(OUTPUT_DIR, "consommations_agregees.parquet")

---

## Chargement des données

In [98]:
## Chargement des données batiments 
df_batiments = pd.read_csv(BATIMENTS_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_batiments.shape}")
print(f"- Colonnes: {df_batiments.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_batiments.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_batiments.head(10)

- Shape: (146, 8)
- Colonnes: ['batiment_id', 'nom', 'type', 'commune', 'surface_m2', 'annee_construction', 'classe_energetique', 'nb_occupants_moyen']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   batiment_id         146 non-null    str
 1   nom                 146 non-null    str
 2   type                146 non-null    str
 3   commune             146 non-null    str
 4   surface_m2          146 non-null    int64
 5   annee_construction  146 non-null    int64
 6   classe_energetique  146 non-null    str
 7   nb_occupants_moyen  146 non-null    int64
dtypes: int64(3), str(5)
memory usage: 15.1 KB

- Appercu des donnees :

,batiment_id,nom,type,commune,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen
0,BAT0001,Ecole Paris 1,ecole,Paris,1926,1978,E,225
1,BAT0002,Ecole Paris 2,ecole,Paris,1156,2004,C,402
2,BAT0003,Ecole Paris 3,ecole,Paris,1695,2014,D,219
3,BAT0004,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121
4,BAT0005,Piscine Paris 5,piscine,Paris,3913,1950,G,242
5,BAT0006,Mairie Paris 6,mairie,Paris,1165,1985,E,63
6,BAT0007,Gymnase Paris 7,gymnase,Paris,1209,1998,C,73
7,BAT0008,Gymnase Paris 8,gymnase,Paris,2236,1955,G,117
8,BAT0009,Ecole Lyon 9,ecole,Lyon,2350,2020,B,140
9,BAT0010,Mediatheque Lyon 10,mediatheque,Lyon,1240,1974,G,103

In [99]:
## Chargement des données consommations à partir du parket (consommations_clean)
df_consommations = pd.read_parquet(CONSOMMATION_PARQUET_DIR)

## Affichage de quelques infos
print(f"- Shape: {df_consommations.shape}")
print(f"- Colonnes: {df_consommations.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_consommations.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_consommations.head(10)

- Shape: (320178, 14)
- Colonnes: ['batiment_id', 'unite', 'year', 'month', 'timestamp_start', 'consommation_mean', 'consommation_min', 'consommation_max', 'measurement_count', 'nom', 'commune', 'type', 'date', 'type_energie']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 320178 entries, 0 to 320177
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   batiment_id        320178 non-null  str
 1   unite              320178 non-null  str
 2   year               320178 non-null  int32
 3   month              320178 non-null  int32
 4   timestamp_start    320178 non-null  datetime64[ns]
 5   consommation_mean  320178 non-null  float64
 6   consommation_min   320178 non-null  float64
 7   consommation_max   320178 non-null  float64
 8   measurement_count  320178 non-null  int64
 9   nom                320178 non-null  str
 10  commune            320178 non-null  str
 11  type               320178 non-null  str
 12  date               320178 non-null  category
 13  type_energie       320178 non-null  category
dtypes: category(2), datetime64[ns](1), float64(3), int32(2), int64(1), str(5)
memory usage: 40.8 MB

- Appercu des donnees :

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom,commune,type,date,type_energie
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau
5,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,Toulouse,mediatheque,2023-01-01,eau
6,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,Saint-Etienne,mediatheque,2023-01-01,eau
7,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,Lyon,ecole,2023-01-01,eau
8,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,Strasbourg,ecole,2023-01-01,eau
9,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,Paris,piscine,2023-01-01,eau

---

## Joindre consommations avec referentiel batiments

In [100]:
## jointure de df_consommations avec df_batiments
df_consommations_batiments = df_consommations.merge(
    df_batiments,
    on="batiment_id",
    how="left"
)

## Affichage de quelques infos
print(f"- Shape: {df_consommations_batiments.shape}")
print(f"- Colonnes: {df_consommations_batiments.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_consommations_batiments.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_consommations_batiments.head(10)

- Shape: (320178, 21)
- Colonnes: ['batiment_id', 'unite', 'year', 'month', 'timestamp_start', 'consommation_mean', 'consommation_min', 'consommation_max', 'measurement_count', 'nom_x', 'commune_x', 'type_x', 'date', 'type_energie', 'nom_y', 'type_y', 'commune_y', 'surface_m2', 'annee_construction', 'classe_energetique', 'nb_occupants_moyen']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 320178 entries, 0 to 320177
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   batiment_id         320178 non-null  str
 1   unite               320178 non-null  str
 2   year                320178 non-null  int32
 3   month               320178 non-null  int32
 4   timestamp_start     320178 non-null  datetime64[ns]
 5   consommation_mean   320178 non-null  float64
 6   consommation_min    320178 non-null  float64
 7   consommation_max    320178 non-null  float64
 8   measurement_count   320178 non-null  int64
 9   nom_x               320178 non-null  str
 10  commune_x           320178 non-null  str
 11  type_x              320178 non-null  str
 12  date                320178 non-null  category
 13  type_energie        320178 non-null  category
 14  nom_y               320178 non-null  str
 15  type_y              320178 non-null  str
 16  commune_y           320178 non-null  str
 17  surface_m2          320178 non-null  int64
 18  annee_construction  320178 non-null  int64
 19  classe_energetique  320178 non-null  str
 20  nb_occupants_moyen  320178 non-null  int64
dtypes: category(2), datetime64[ns](1), float64(3), int32(2), int64(4), str(9)
memory usage: 68.3 MB

- Appercu des donnees :

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,...,type_x,date,type_energie,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,...,ecole,2023-01-01,eau,Ecole Marseille 29,ecole,Marseille,2022,2014,D,427
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,...,ecole,2023-01-01,eau,Ecole Paris 3,ecole,Paris,1695,2014,D,219
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,...,mairie,2023-01-01,eau,Mairie Nice 96,mairie,Nice,473,2015,D,56
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,...,mediatheque,2023-01-01,eau,Mediatheque Toulouse 36,mediatheque,Toulouse,1994,1975,G,118
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,...,mediatheque,2023-01-01,eau,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121
5,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,...,mediatheque,2023-01-01,eau,Mediatheque Toulouse 34,mediatheque,Toulouse,757,2010,D,46
6,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,...,mediatheque,2023-01-01,eau,Mediatheque Saint-Etienne 131,mediatheque,Saint-Etienne,584,2018,C,74
7,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,...,ecole,2023-01-01,eau,Ecole Lyon 18,ecole,Lyon,1664,1990,D,390
8,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,...,ecole,2023-01-01,eau,Ecole Strasbourg 70,ecole,Strasbourg,814,1966,G,270
9,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,...,piscine,2023-01-01,eau,Piscine Paris 5,piscine,Paris,3913,1950,G,242

---

## Calculer l'intensite energetique (kWh/m2)

In [101]:
## Filtrer l’électricité
df_elec = df_consommations_batiments[df_consommations_batiments["type_energie"] == "electricite"].copy()
# df_elec.head()

## Calcul de l’intensité énergétique (kWh/m²)
df_elec["intensite_energetique_kwh_m2"] = (
    df_elec["consommation_mean"] / df_elec["surface_m2"]
).round(3)

df_elec.head()

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,...,date,type_energie,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen,intensite_energetique_kwh_m2
146,BAT0004,kWh,2023,1,2023-01-01,73.15,6.48,147.05,24,Mediatheque Paris 4,...,2023-01-01,electricite,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121,0.081
147,BAT0001,kWh,2023,1,2023-01-01,53.21,5.70,105.18,24,Ecole Paris 1,...,2023-01-01,electricite,Ecole Paris 1,ecole,Paris,1926,1978,E,225,0.028
148,BAT0134,kWh,2023,1,2023-01-01,1183.26,112.57,2096.11,23,Piscine Saint-Etienne 134,...,2023-01-01,electricite,Piscine Saint-Etienne 134,piscine,Saint-Etienne,2126,1972,G,322,0.557
149,BAT0129,kWh,2023,1,2023-01-01,9.73,1.17,18.47,23,Mairie Saint-Etienne 129,...,2023-01-01,electricite,Mairie Saint-Etienne 129,mairie,Saint-Etienne,455,1981,E,95,0.021
150,BAT0034,kWh,2023,1,2023-01-01,69.08,8.08,128.66,23,Mediatheque Toulouse 34,...,2023-01-01,electricite,Mediatheque Toulouse 34,mediatheque,Toulouse,757,2010,D,46,0.091

---

## Identifier les batiments hors norme (>3x la mediane de leur categorie)

- Catégorie = type_y
- Indicateur = intensite_energetique_kwh_m2
- Règle = > 3 × médiane de la catégorie

In [102]:
df_elec_med = df_elec.merge(
    df_elec.groupby("type_y")["intensite_energetique_kwh_m2"]
    .median()
    .rename("mediane_type"),
    on="type_y"
)

df_hors_norme = df_elec_med[
    df_elec_med["intensite_energetique_kwh_m2"] > 3 * df_elec_med["mediane_type"]
]

df_hors_norme.head()

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,...,type_energie,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen,intensite_energetique_kwh_m2,mediane_type
865,BAT0124,kWh,2023,1,2023-01-06 00:00:00,214.37,18.64,397.01,22,Ecole Le Havre 124,...,electricite,Ecole Le Havre 124,ecole,Le Havre,927,1975,G,226,0.231,0.077
2543,BAT0075,kWh,2023,1,2023-01-18 00:00:00,522.67,53.95,914.84,23,Ecole Strasbourg 75,...,electricite,Ecole Strasbourg 75,ecole,Strasbourg,2265,1981,G,207,0.231,0.077
4552,BAT0137,kWh,2023,2,2023-02-01 01:00:00,452.39,41.81,821.57,23,Ecole Toulon 137,...,electricite,Ecole Toulon 137,ecole,Toulon,1942,1981,G,330,0.233,0.077
5488,BAT0023,kWh,2023,2,2023-02-07 00:00:00,329.35,26.17,583.88,23,Ecole Marseille 23,...,electricite,Ecole Marseille 23,ecole,Marseille,1426,1970,G,421,0.231,0.077
5516,BAT0137,kWh,2023,2,2023-02-07 00:00:00,450.90,53.26,832.90,23,Ecole Toulon 137,...,electricite,Ecole Toulon 137,ecole,Toulon,1942,1981,G,330,0.232,0.077

---

## Calculer les totaux par commune et par type de batiment

In [103]:
df_totaux = (
    df_elec.groupby(["commune_y", "type_y"], as_index=False)
    .agg(
        consommation_totale_kwh=("consommation_mean", "sum"),
        nb_batiments=("batiment_id", "nunique"),
        intensite_energetique_moyenne=("intensite_energetique_kwh_m2", "mean")
    )
)
df_totaux.head()

,commune_y,type_y,consommation_totale_kwh,nb_batiments,intensite_energetique_moyenne
0,Bordeaux,ecole,190599.98,2,0.084094
1,Bordeaux,gymnase,211594.29,1,0.155042
2,Bordeaux,mairie,118935.88,3,0.060515
3,Bordeaux,mediatheque,156652.33,1,0.127557
4,Bordeaux,piscine,607683.84,1,0.364766

---

## Creer une vue SQL exploitable

In [104]:
import sqlite3

## Création d'une base en mémoire
conn = sqlite3.connect(":memory:")

## Chargement du DataFrame df_elec comme table SQL
df_elec.to_sql("consommations", conn, index=False, if_exists="replace")

## Exemple de requêtes SQL exploitables (Tous les bâtiments électriques)
query = """
SELECT
    batiment_id,
    nom_y,
    type_y,
    commune_y,
    intensite_energetique_kwh_m2
FROM consommations
"""

df_sql = pd.read_sql(query, conn)
df_sql.head()

,batiment_id,nom_y,type_y,commune_y,intensite_energetique_kwh_m2
0,BAT0004,Mediatheque Paris 4,mediatheque,Paris,0.081
1,BAT0001,Ecole Paris 1,ecole,Paris,0.028
2,BAT0134,Piscine Saint-Etienne 134,piscine,Saint-Etienne,0.557
3,BAT0129,Mairie Saint-Etienne 129,mairie,Saint-Etienne,0.021
4,BAT0034,Mediatheque Toulouse 34,mediatheque,Toulouse,0.091

---

## Table agregee consommations_agregees.parquet

- Agrégation par : commune, type de bâtiment, année, énergie
- Avec : consommation totale, intensité énergétique moyenne, nombre de bâtiments

In [105]:
## Création d'une table agrégée
df_agregee = (
    df_elec
    .groupby(
        ["commune_y", "type_y", "year", "type_energie"],
        as_index=False
    )
    .agg(
        consommation_totale_kwh=("consommation_mean", "sum"),
        intensite_moyenne_kwh_m2=("intensite_energetique_kwh_m2", "mean"),
        nb_batiments=("batiment_id", "nunique")
    )
)

## Renommage des colonnes
df_agregee = df_agregee.rename(columns={
    "commune_y": "commune",
    "type_y": "type_batiment"
})

## Écriture de la table en Parquet
df_agregee.to_parquet(
    CONSO_AGREGEES_PARKET,
    engine="pyarrow",
    index=False
)

---

## Check du parquet

In [106]:
df_check = pd.read_parquet(CONSO_AGREGEES_PARKET)
df_check.head()

,commune,type_batiment,year,type_energie,consommation_totale_kwh,intensite_moyenne_kwh_m2,nb_batiments
0,Bordeaux,ecole,2023,electricite,94778.54,0.083773,2
1,Bordeaux,ecole,2024,electricite,95821.44,0.084415,2
2,Bordeaux,gymnase,2023,electricite,105423.74,0.154696,1
3,Bordeaux,gymnase,2024,electricite,106170.55,0.155388,1
4,Bordeaux,mairie,2023,electricite,59120.71,0.060212,3