# Etape 2.1 : Nettoyage des donnees meteos

**Objectif** : Traiter des donnees structurees avec un langage de programmation

---
---

## Imports

In [103]:
import sys
import os
from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np

---

## Chemins des données

In [104]:
DATA_DIR = (Path.cwd() / ".." / "data").resolve()
OUTPUT_DIR = os.path.join(DATA_DIR, "output")
PARQUET_DIR = os.path.join(OUTPUT_DIR, "consommations_clean")
WEATHER_PATH = os.path.join(DATA_DIR, "meteo_raw.csv")

---

## Chargement du fichier meteo_raw.csv avec Pandas (les données météo brutes)

In [105]:
## Chargement des données avec Pandas
df_weather_raw = pd.read_csv(WEATHER_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_weather_raw.shape}")
print(f"- Colonnes: {df_weather_raw.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_weather_raw.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_weather_raw.head(10)

- Shape: (252612, 7)
- Colonnes: ['commune', 'timestamp', 'temperature_c', 'humidite_pct', 'rayonnement_solaire_wm2', 'vitesse_vent_kmh', 'precipitation_mm']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 252612 entries, 0 to 252611
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   commune                  252612 non-null  str
 1   timestamp                252612 non-null  str
 2   temperature_c            251383 non-null  str
 3   humidite_pct             252612 non-null  float64
 4   rayonnement_solaire_wm2  252612 non-null  float64
 5   vitesse_vent_kmh         252612 non-null  float64
 6   precipitation_mm         252612 non-null  float64
dtypes: float64(4), str(3)
memory usage: 13.5 MB

- Appercu des donnees :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm
0,Saint-Etienne,09/15/2024 15:00:00,17.1,143.3,244.9,14.3,0.0
1,Bordeaux,21/07/2023 15:00,19.6,50.6,414.9,3.2,0.0
2,Montpellier,2023-09-18 20:00:00,18.3,65.7,218.4,13.6,0.0
3,Le Havre,01/03/2024 22:00:00,3.7,94.9,6.8,18.6,11.6
4,Lille,29/10/2024 20:00,14.0,42.9,781.8,4.0,0.0
5,Bordeaux,22/12/2023 13:00,4.4,36.9,796.4,6.1,0.0
6,Marseille,09/15/2023 21:00:00,22.5,86.8,5.8,32.6,0.0
7,Toulouse,30/05/2023 00:00,8.3,66.3,26.4,31.4,7.2
8,Bordeaux,2024-10-05T09:00:00,11.5,69.8,71.4,34.4,0.0
9,Toulon,2024-09-28T21:00:00,19.2,79.0,13.1,31.8,0.0

---

## Standardiser les formats de dates

In [106]:
def parse_timestamp(ts):
    """Parse les timestamps multi-formats."""
    if pd.isna(ts):
        return pd.NaT
    
    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%d/%m/%Y %H:%M",
        "%m/%d/%Y %H:%M:%S",
        "%Y-%m-%dT%H:%M:%S",
    ]
    
    for fmt in formats:
        try:
            return datetime.strptime(str(ts), fmt)
        except ValueError:
            continue
    
    return pd.NaT

df_weather = df_weather_raw.copy()

## 1. Parser les timestamps
print("[1/5] Parsing des timestamps ...")
df_weather['timestamp'] = df_weather['timestamp'].apply(parse_timestamp)
invalid_ts = df_weather['timestamp'].isna().sum()
print(f"    - Timestamps invalides: {invalid_ts}")

## Supprimer les lignes sans timestamp valide
df_weather = df_weather.dropna(subset=['timestamp'])

## Affichage de quelques infos
print("\n- Affichage des infos meteo après standarisation des format des dates :")
print(f"- Shape: {df_weather.shape}")
print(f"- Colonnes: {df_weather.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_weather.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_weather.head(10)

[1/5] Parsing des timestamps ...
    - Timestamps invalides: 0

- Affichage des infos meteo après standarisation des format des dates :
- Shape: (252612, 7)
- Colonnes: ['commune', 'timestamp', 'temperature_c', 'humidite_pct', 'rayonnement_solaire_wm2', 'vitesse_vent_kmh', 'precipitation_mm']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 252612 entries, 0 to 252611
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   commune                  252612 non-null  str
 1   timestamp                252612 non-null  datetime64[us]
 2   temperature_c            251383 non-null  str
 3   humidite_pct             252612 non-null  float64
 4   rayonnement_solaire_wm2  252612 non-null  float64
 5   vitesse_vent_kmh         252612 non-null  float64
 6   precipitation_mm         252612 non-null  float64
dtypes: datetime64[us](1), float64(4), str(2)
memory usage: 13.5 MB

- Appercu des donnees :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm
0,Saint-Etienne,2024-09-15 15:00:00,17.1,143.3,244.9,14.3,0.0
1,Bordeaux,2023-07-21 15:00:00,19.6,50.6,414.9,3.2,0.0
2,Montpellier,2023-09-18 20:00:00,18.3,65.7,218.4,13.6,0.0
3,Le Havre,2024-01-03 22:00:00,3.7,94.9,6.8,18.6,11.6
4,Lille,2024-10-29 20:00:00,14.0,42.9,781.8,4.0,0.0
5,Bordeaux,2023-12-22 13:00:00,4.4,36.9,796.4,6.1,0.0
6,Marseille,2023-09-15 21:00:00,22.5,86.8,5.8,32.6,0.0
7,Toulouse,2023-05-30 00:00:00,8.3,66.3,26.4,31.4,7.2
8,Bordeaux,2024-10-05 09:00:00,11.5,69.8,71.4,34.4,0.0
9,Toulon,2024-09-28 21:00:00,19.2,79.0,13.1,31.8,0.0

---

## Convertir les colonnes numeriques en gerant les erreurs

Les colonnes numeriques : temperature_c, humidite_pct, rayonnement_solaire_wm2, vitesse_vent_kmh, precipitation_mm

In [107]:
## 2. Convertir les colonnes numeriques
print("\n[2/5] Conversion des colonnes numeriques ...")

## Temperature (remplacer virgule par point)
df_weather['temperature_c'] = pd.to_numeric(
    df_weather['temperature_c'].astype(str).str.replace(',', '.'),
    errors='coerce' # Si une valeur ne peut pas être convertie en nombre, transforme-la en NaN
)

## Autres colonnes
df_weather['humidite_pct'] = pd.to_numeric(df_weather['humidite_pct'], errors='coerce')
df_weather['rayonnement_solaire_wm2'] = pd.to_numeric(df_weather['rayonnement_solaire_wm2'], errors='coerce')
df_weather['vitesse_vent_kmh'] = pd.to_numeric(df_weather['vitesse_vent_kmh'], errors='coerce')
df_weather['precipitation_mm'] = pd.to_numeric(df_weather['precipitation_mm'], errors='coerce')

print("  - Conversions effectuees.")

## Appercu des donnees
print("  - Appercu des donnees après la convertion des colonnes numeriques : ")
df_weather.head(10)

[2/5] Conversion des colonnes numeriques ...
  - Conversions effectuees.
  - Appercu des donnees après la convertion des colonnes numeriques :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm
0,Saint-Etienne,2024-09-15 15:00:00,17.1,143.3,244.9,14.3,0.0
1,Bordeaux,2023-07-21 15:00:00,19.6,50.6,414.9,3.2,0.0
2,Montpellier,2023-09-18 20:00:00,18.3,65.7,218.4,13.6,0.0
3,Le Havre,2024-01-03 22:00:00,3.7,94.9,6.8,18.6,11.6
4,Lille,2024-10-29 20:00:00,14.0,42.9,781.8,4.0,0.0
5,Bordeaux,2023-12-22 13:00:00,4.4,36.9,796.4,6.1,0.0
6,Marseille,2023-09-15 21:00:00,22.5,86.8,5.8,32.6,0.0
7,Toulouse,2023-05-30 00:00:00,8.3,66.3,26.4,31.4,7.2
8,Bordeaux,2024-10-05 09:00:00,11.5,69.8,71.4,34.4,0.0
9,Toulon,2024-09-28 21:00:00,19.2,79.0,13.1,31.8,0.0

---

## Corriger les valeurs aberrantes :

  - Temperatures hors [-40, 50] -> NaN puis interpolation
  - Humidite hors [0, 100] -> clipping
  - Rayonnement solaire negatif -> 0

In [108]:
## 3. Corriger les valeurs aberrantes
print("\n[3/5] Correction des valeurs aberrantes ...")

## Temperatures hors [-40, 50] -> NaN
temp_outliers = ((df_weather['temperature_c'] < -40) | (df_weather['temperature_c'] > 50)).sum()
df_weather.loc[
    (df_weather['temperature_c'] < -40) | (df_weather['temperature_c'] > 50),
    'temperature_c'
] = np.nan
print(f"  - Temperatures aberrantes -> NaN : {temp_outliers}")

## Humidite hors [0, 100] -> clipper
humidity_outliers = ((df_weather['humidite_pct'] < 0) | (df_weather['humidite_pct'] > 100)).sum()
df_weather['humidite_pct'] = df_weather['humidite_pct'].clip(0, 100)
print(f"  - Humidite clippee [0, 100] -> : {humidity_outliers}")

## Rayonnement solaire negatif -> 0
rayonnement_outliers = ((df_weather['rayonnement_solaire_wm2'] < 0)).sum()
df_weather['rayonnement_solaire_wm2'] = df_weather['rayonnement_solaire_wm2'].clip(lower=0)
print(f"  - Rayonnement solaire clippee (< 0) -> 0 : {rayonnement_outliers}")

[3/5] Correction des valeurs aberrantes ...
  - Temperatures aberrantes -> NaN : 1977
  - Humidite clippee [0, 100] -> : 1801
  - Rayonnement solaire clippee (< 0) -> 0 : 1275

---

## Traiter les valeurs manquantes :

  - Interpolation lineaire pour temperature et humidite
  - Forward fill pour precipitation

In [109]:
## 4. Traiter les valeurs manquantes
print("[4/5] Traitement des valeurs manquantes ...")

## Trier par commune et timestamp pour l'interpolation
df_weather = df_weather.sort_values(['commune', 'timestamp'])

## Interpolation lineaire pour temperature et humidite (par commune)
for col in ['temperature_c', 'humidite_pct', 'vitesse_vent_kmh', 'precipitation_mm']:
    before_na = df_weather[col].isna().sum()
    df_weather[col] = df_weather.groupby('commune')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )
    after_na = df_weather[col].isna().sum()
    print(f"  - {col}: {before_na} -> {after_na} NaN (interpoles: {before_na - after_na})")

## Forward fill pour precipitation_mm
before_na = (df_weather['precipitation_mm'].isna() | (df_weather['precipitation_mm'] == '')).sum()
df_weather['precipitation_mm'] = df_weather['precipitation_mm'].replace('', np.nan)
df_weather['precipitation_mm'] = df_weather.groupby('commune')['precipitation_mm'].transform(
    lambda x: x.ffill().bfill()
)
after_na = df_weather['precipitation_mm'].isna().sum()
print(f"  - precipitation_mm: {before_na} -> {after_na} NaN (forward filled)")

[4/5] Traitement des valeurs manquantes ...
  - temperature_c: 3206 -> 0 NaN (interpoles: 3206)
  - humidite_pct: 0 -> 0 NaN (interpoles: 0)
  - vitesse_vent_kmh: 0 -> 0 NaN (interpoles: 0)
  - precipitation_mm: 0 -> 0 NaN (interpoles: 0)
  - precipitation_mm: 0 -> 0 NaN (forward filled)

---

## Ajouter des colonnes temporelles (jour, mois, saison, jour de semaine)

In [110]:
## 5. Ajouter des colonnes temporelles
print("[5/5] Ajout des colonnes temporelles ...")

df_weather['jour'] = df_weather['timestamp'].dt.date
df_weather['jour_de_semaine'] = df_weather['timestamp'].dt.dayofweek
df_weather['mois'] = df_weather['timestamp'].dt.month
df_weather['saison'] = df_weather['mois'].map({
    12: 'Hiver', 1: 'Hiver', 2: 'Hiver',
    3: 'Printemps', 4: 'Printemps', 5: 'Printemps',
    6: 'Ete', 7: 'Ete', 8: 'Ete',
    9: 'Automne', 10: 'Automne', 11: 'Automne'
})

print("  - Colonnes ajoutees: jour, hour, jour_de_semaine, mois, saison")

print("  - Appercu des données meteo nettoyées : ")
df_weather.head(100)

[5/5] Ajout des colonnes temporelles ...
  - Colonnes ajoutees: jour, hour, jour_de_semaine, mois, saison
  - Appercu des données meteo nettoyées :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm,jour,jour_de_semaine,mois,saison
242272,Bordeaux,2023-01-01 00:00:00,8.5,43.9,0.8,0.2,0.0,2023-01-01,6,1,Hiver
233980,Bordeaux,2023-01-01 01:00:00,2.7,39.7,6.1,21.5,5.3,2023-01-01,6,1,Hiver
108665,Bordeaux,2023-01-01 02:00:00,6.2,78.9,49.5,13.1,0.0,2023-01-01,6,1,Hiver
5904,Bordeaux,2023-01-01 03:00:00,10.3,64.2,24.3,0.6,14.7,2023-01-01,6,1,Hiver
23544,Bordeaux,2023-01-01 04:00:00,0.9,36.4,20.7,35.6,0.0,2023-01-01,6,1,Hiver
...,...,...,...,...,...,...,...,...,...,...,...
136540,Bordeaux,2023-01-05 01:00:00,11.1,62.4,39.7,33.2,1.6,2023-01-05,3,1,Hiver
215487,Bordeaux,2023-01-05 02:00:00,2.5,50.5,6.2,17.6,0.0,2023-01-05,3,1,Hiver
59654,Bordeaux,2023-01-05 03:00:00,8.2,48.2,45.0,2.3,0.0,2023-01-05,3,1,Hiver
99492,Bordeaux,2023-01-05 04:00:00,9.2,76.0,24.9,10.9,0.0,2023-01-05,3,1,Hiver
177101,Bordeaux,2023-01-05 05:00:00,8.3,30.2,11.9,15.3,0.0,2023-01-05,3,1,Hiver

---

## Création du Dataset nettoye output/meteo_clean.csv (Save DataFrame to CSV)

In [111]:
meteo_clean_path = os.path.join(OUTPUT_DIR,"meteo_clean.csv")
df_weather.to_csv(meteo_clean_path, index=False)

---

## Rapport avant/apres nettoyage (completude par colonne)

In [112]:
## Rapport final
print("RAPPORT DE NETTOYAGE - DONNEES METEO")
print(f"- Lignes brutes: {len(df_weather_raw):,}")
print(f"- Lignes apres nettoyage: {len(df_weather):,}")
print(f"- Lignes supprimees: {len(df_weather_raw) - len(df_weather):,}")
print("\nCompletude finale:")
for col in ['temperature_c', 'humidite_pct', 'vitesse_vent_kmh', 'precipitation_mm', 'precipitation_mm']:
    completude = (1 - df_weather[col].isna().sum() / len(df_weather)) * 100
    print(f"  {col}: {completude:.2f}%")

RAPPORT DE NETTOYAGE - DONNEES METEO
- Lignes brutes: 252,612
- Lignes apres nettoyage: 252,612
- Lignes supprimees: 0

Completude finale:
  temperature_c: 100.00%
  humidite_pct: 100.00%
  vitesse_vent_kmh: 100.00%
  precipitation_mm: 100.00%
  precipitation_mm: 100.00%