# Etape 2.2 : Fusion et enrichissement

---
---

## Import

In [43]:
import sys
import os
from pathlib import Path
import pandas as pd
pd.set_option('display.max_columns', None)

---

## Chemins des données

In [44]:
DATA_DIR = (Path.cwd() / ".." / "data").resolve()
OUTPUT_DIR = os.path.join(DATA_DIR, "output")
PARQUET_DIR = os.path.join(OUTPUT_DIR, "consommations_clean")
WEATHER_CLEAN_PATH = os.path.join(OUTPUT_DIR, "meteo_clean.csv")
BATIMENT_PATH = os.path.join(DATA_DIR, "batiments.csv")
TARIF_PATH = os.path.join(DATA_DIR, "tarifs_energie.csv")

---

## Charger les consommations nettoyees (depuis Parquet)

In [45]:
df_consommations = pd.read_parquet(PARQUET_DIR)

## Affichage de quelques infos
print(f"- Shape: {df_consommations.shape}")
print(f"- Colonnes: {df_consommations.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_consommations.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_consommations.head(10)

- Shape: (320178, 14)
- Colonnes: ['batiment_id', 'unite', 'year', 'month', 'timestamp_start', 'consommation_mean', 'consommation_min', 'consommation_max', 'measurement_count', 'nom', 'commune', 'type', 'date', 'type_energie']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 320178 entries, 0 to 320177
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   batiment_id        320178 non-null  str
 1   unite              320178 non-null  str
 2   year               320178 non-null  int32
 3   month              320178 non-null  int32
 4   timestamp_start    320178 non-null  datetime64[ns]
 5   consommation_mean  320178 non-null  float64
 6   consommation_min   320178 non-null  float64
 7   consommation_max   320178 non-null  float64
 8   measurement_count  320178 non-null  int64
 9   nom                320178 non-null  str
 10  commune            320178 non-null  str
 11  type               320178 non-null  str
 12  date               320178 non-null  category
 13  type_energie       320178 non-null  category
dtypes: category(2), datetime64[ns](1), float64(3), int32(2), int64(1), str(5)
memory usage: 40.8 MB

- Appercu des donnees :

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom,commune,type,date,type_energie
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau
5,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,Toulouse,mediatheque,2023-01-01,eau
6,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,Saint-Etienne,mediatheque,2023-01-01,eau
7,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,Lyon,ecole,2023-01-01,eau
8,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,Strasbourg,ecole,2023-01-01,eau
9,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,Paris,piscine,2023-01-01,eau

---

## Charger les données météo nettoyees

In [46]:
df_weather = pd.read_csv(WEATHER_CLEAN_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_weather.shape}")
print(f"- Colonnes: {df_weather.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_weather.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_weather.head(10)

- Shape: (252612, 11)
- Colonnes: ['commune', 'timestamp', 'temperature_c', 'humidite_pct', 'rayonnement_solaire_wm2', 'vitesse_vent_kmh', 'precipitation_mm', 'jour', 'jour_de_semaine', 'mois', 'saison']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 252612 entries, 0 to 252611
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   commune                  252612 non-null  str
 1   timestamp                252612 non-null  str
 2   temperature_c            252612 non-null  float64
 3   humidite_pct             252612 non-null  float64
 4   rayonnement_solaire_wm2  252612 non-null  float64
 5   vitesse_vent_kmh         252612 non-null  float64
 6   precipitation_mm         252612 non-null  float64
 7   jour                     252612 non-null  str
 8   jour_de_semaine          252612 non-null  int64
 9   mois                     252612 non-null  int64
 10  saison                   252612 non-null  str
dtypes: float64(5), int64(2), str(4)
memory usage: 31.4 MB

- Appercu des donnees :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm,jour,jour_de_semaine,mois,saison
0,Bordeaux,2023-01-01 00:00:00,8.5,43.9,0.8,0.2,0.0,2023-01-01,6,1,Hiver
1,Bordeaux,2023-01-01 01:00:00,2.7,39.7,6.1,21.5,5.3,2023-01-01,6,1,Hiver
2,Bordeaux,2023-01-01 02:00:00,6.2,78.9,49.5,13.1,0.0,2023-01-01,6,1,Hiver
3,Bordeaux,2023-01-01 03:00:00,10.3,64.2,24.3,0.6,14.7,2023-01-01,6,1,Hiver
4,Bordeaux,2023-01-01 04:00:00,0.9,36.4,20.7,35.6,0.0,2023-01-01,6,1,Hiver
5,Bordeaux,2023-01-01 05:00:00,7.9,66.0,5.9,0.3,0.0,2023-01-01,6,1,Hiver
6,Bordeaux,2023-01-01 06:00:00,1.6,40.2,392.3,24.3,0.0,2023-01-01,6,1,Hiver
7,Bordeaux,2023-01-01 07:00:00,4.9,87.9,781.5,27.9,0.0,2023-01-01,6,1,Hiver
8,Bordeaux,2023-01-01 08:00:00,8.4,43.4,565.0,38.8,0.1,2023-01-01,6,1,Hiver
9,Bordeaux,2023-01-01 09:00:00,10.1,83.8,52.3,25.4,0.0,2023-01-01,6,1,Hiver

---

## Chargement du referenciel batiments

In [47]:
df_batiments = pd.read_csv(BATIMENT_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_batiments.shape}")
print(f"- Colonnes: {df_batiments.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_batiments.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_batiments.head(10)

- Shape: (146, 8)
- Colonnes: ['batiment_id', 'nom', 'type', 'commune', 'surface_m2', 'annee_construction', 'classe_energetique', 'nb_occupants_moyen']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   batiment_id         146 non-null    str
 1   nom                 146 non-null    str
 2   type                146 non-null    str
 3   commune             146 non-null    str
 4   surface_m2          146 non-null    int64
 5   annee_construction  146 non-null    int64
 6   classe_energetique  146 non-null    str
 7   nb_occupants_moyen  146 non-null    int64
dtypes: int64(3), str(5)
memory usage: 15.1 KB

- Appercu des donnees :

,batiment_id,nom,type,commune,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen
0,BAT0001,Ecole Paris 1,ecole,Paris,1926,1978,E,225
1,BAT0002,Ecole Paris 2,ecole,Paris,1156,2004,C,402
2,BAT0003,Ecole Paris 3,ecole,Paris,1695,2014,D,219
3,BAT0004,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121
4,BAT0005,Piscine Paris 5,piscine,Paris,3913,1950,G,242
5,BAT0006,Mairie Paris 6,mairie,Paris,1165,1985,E,63
6,BAT0007,Gymnase Paris 7,gymnase,Paris,1209,1998,C,73
7,BAT0008,Gymnase Paris 8,gymnase,Paris,2236,1955,G,117
8,BAT0009,Ecole Lyon 9,ecole,Lyon,2350,2020,B,140
9,BAT0010,Mediatheque Lyon 10,mediatheque,Lyon,1240,1974,G,103

---

## Chargement des tarifs

In [48]:
df_tarifs = pd.read_csv(TARIF_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_tarifs.shape}")
print(f"- Colonnes: {df_tarifs.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_tarifs.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_tarifs.head()

- Shape: (10, 4)
- Colonnes: ['date_debut', 'date_fin', 'type_energie', 'tarif_unitaire']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_debut      10 non-null     str
 1   date_fin        10 non-null     str
 2   type_energie    10 non-null     str
 3   tarif_unitaire  10 non-null     float64
dtypes: float64(1), str(3)
memory usage: 714.0 bytes

- Appercu des donnees :

   date_debut    date_fin type_energie  tarif_unitaire
0  2023-01-01  2023-06-30  electricite            0.18
1  2023-07-01  2023-12-31  electricite            0.20
2  2023-01-01  2023-06-30          gaz            0.09
3  2023-07-01  2023-12-31          gaz            0.10
4  2023-01-01  2023-12-31          eau            3.50

---

## Fusionner avec les donnees meteo (sur commune et timestamp arrondi a l'heure)

In [49]:
## Preparer les donnees pour la fusion

## Verifier si les donnees de consommation sont vides
if len(df_consommations) == 0:
    print("ATTENTION: Les donnees de consommation sont vides!")
    print("Veuillez d'abord executer le notebook 02 pour generer les donnees Parquet.")
    # Creer un DataFrame vide avec les bonnes colonnes pour eviter les erreurs
    df_consommations['datetime_hour'] = pd.to_datetime([])
else:
    ## Pour la consommation: creer une colonne datetime arrondie a l'heure
    if 'date' in df_consommations.columns and 'hour' in df_consommations.columns:
        df_consommations['datetime_hour'] = pd.to_datetime(
            df_consommations['date'].astype(str) + ' ' + df_consommations['hour'].astype(str) + ':00:00'
        )
    elif 'timestamp_start' in df_consommations.columns:
        df_consommations['datetime_hour'] = df_consommations['timestamp_start'].dt.floor('h')
    elif 'timestamp' in df_consommations.columns:
        df_consommations['datetime_hour'] = df_consommations['timestamp'].dt.floor('h')
    else:
        print("- ERREUR: Aucune colonne temporelle trouvee dans df_consommation")
        df_consommations['datetime_hour'] = pd.to_datetime([])

## Pour la meteo: arrondir a l'heure
df_weather['timestamp'] = pd.to_datetime(
    df_weather['timestamp'],
    errors='coerce'
)

df_weather['datetime_hour'] = df_weather['timestamp'].dt.floor('h')

if len(df_consommations) > 0:
    print(f"- Consommations : {df_consommations['datetime_hour'].min()} -> {df_consommations['datetime_hour'].max()}")
print(f"- Meteo: {df_weather['datetime_hour'].min()} -> {df_weather['datetime_hour'].max()}")

- Consommations : 2023-01-01 00:00:00 -> 2024-12-31 01:00:00
- Meteo: 2023-01-01 00:00:00 -> 2024-12-31 23:00:00

In [50]:
## Agreger la meteo par commune et heure (au cas ou il y aurait des doublons)
df_weather_hourly = df_weather.groupby(['commune', 'datetime_hour']).agg({
    'temperature_c': 'mean', # → smooths multiple measurements in the same hour
    'humidite_pct': 'mean',
    'vitesse_vent_kmh': 'mean',
    'precipitation_mm': 'sum', # → correct: rainfall accumulates
    'precipitation_mm': 'first', # → assumes these don’t change within the hour
    'saison': 'first'
}).reset_index() # Converts group keys back into normal columns => Makes the DataFrame easier to work with later

print(f"- Meteo agregee: {len(df_weather_hourly):,} lignes")

- Meteo agregee: 252,612 lignes

In [51]:
## Fusion sur commune et datetime_hour
if len(df_consommations) == 0:
    print("ERREUR: Impossible de fusionner - les donnees de consommations sont vides!")
    print("Veuillez d'abord executer le notebook 02_nettoyage_spark.ipynb")
    df_merged = pd.DataFrame()
else:
    df_merged = df_consommations.merge(
        df_weather_hourly,
        on=['commune', 'datetime_hour'],
        how='left'
    )

    print(f"\nResultat de la fusion:")
    print(f"  - Lignes consommations: {len(df_consommations):,}")
    print(f"  - Lignes apres fusion: {len(df_merged):,}")
    print(f"  - Lignes avec meteo: {df_merged['temperature_c'].notna().sum():,}")
    print(f"  - Lignes sans meteo: {df_merged['temperature_c'].isna().sum():,}")

Resultat de la fusion:
  - Lignes consommations: 320,178
  - Lignes apres fusion: 320,178
  - Lignes avec meteo: 307,733
  - Lignes sans meteo: 12,445

In [52]:
## Apercu du dataset fusionne
df_merged.head(10)

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom,commune,type,date,type_energie,datetime_hour,temperature_c,humidite_pct,vitesse_vent_kmh,precipitation_mm,saison
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau,2023-01-01,6.4,88.7,3.9,0.0,Hiver
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau,2023-01-01,15.8,41.2,33.8,0.0,Hiver
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver
5,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver
6,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,Saint-Etienne,mediatheque,2023-01-01,eau,2023-01-01,-0.5,90.7,19.7,0.0,Hiver
7,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,Lyon,ecole,2023-01-01,eau,2023-01-01,10.7,72.1,14.8,0.0,Hiver
8,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,Strasbourg,ecole,2023-01-01,eau,2023-01-01,3.7,52.0,8.7,0.0,Hiver
9,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,Paris,piscine,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver

---

## Fusionner avec le referentiel batiments

In [53]:
df_conso_bat = df_merged.merge(
        df_batiments,
        on=['batiment_id'],
        how='left'
)

## Affichage de quelques infos
print(f"- Shape: {df_conso_bat.shape}")
print(f"- Colonnes: {df_conso_bat.columns.tolist()}")
df_conso_bat.head(10)

- Shape: (320178, 27)
- Colonnes: ['batiment_id', 'unite', 'year', 'month', 'timestamp_start', 'consommation_mean', 'consommation_min', 'consommation_max', 'measurement_count', 'nom_x', 'commune_x', 'type_x', 'date', 'type_energie', 'datetime_hour', 'temperature_c', 'humidite_pct', 'vitesse_vent_kmh', 'precipitation_mm', 'saison', 'nom_y', 'type_y', 'commune_y', 'surface_m2', 'annee_construction', 'classe_energetique', 'nb_occupants_moyen']

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,commune_x,type_x,date,type_energie,datetime_hour,temperature_c,humidite_pct,vitesse_vent_kmh,precipitation_mm,saison,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau,2023-01-01,6.4,88.7,3.9,0.0,Hiver,Ecole Marseille 29,ecole,Marseille,2022,2014,D,427
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Ecole Paris 3,ecole,Paris,1695,2014,D,219
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau,2023-01-01,15.8,41.2,33.8,0.0,Hiver,Mairie Nice 96,mairie,Nice,473,2015,D,56
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 36,mediatheque,Toulouse,1994,1975,G,118
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121
5,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 34,mediatheque,Toulouse,757,2010,D,46
6,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,Saint-Etienne,mediatheque,2023-01-01,eau,2023-01-01,-0.5,90.7,19.7,0.0,Hiver,Mediatheque Saint-Etienne 131,mediatheque,Saint-Etienne,584,2018,C,74
7,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,Lyon,ecole,2023-01-01,eau,2023-01-01,10.7,72.1,14.8,0.0,Hiver,Ecole Lyon 18,ecole,Lyon,1664,1990,D,390
8,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,Strasbourg,ecole,2023-01-01,eau,2023-01-01,3.7,52.0,8.7,0.0,Hiver,Ecole Strasbourg 70,ecole,Strasbourg,814,1966,G,270
9,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,Paris,piscine,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Piscine Paris 5,piscine,Paris,3913,1950,G,242

---

## Fusionner avec les tarifs pour calculer le cout financier

In [54]:
df_merge = df_conso_bat.merge(df_tarifs, on="type_energie", how="left")

for col in ["date", "date_debut", "date_fin"]:
    df_merge[col] = pd.to_datetime(df_merge[col].astype(str), errors="coerce")

df_merge = df_merge[
    (df_merge["date"] >= df_merge["date_debut"]) &
    (df_merge["date"] <= df_merge["date_fin"])
]

df_merge["cout_financier"] = (
    df_merge["consommation_mean"] * df_merge["tarif_unitaire"]
)
df_merge.head(10)

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,commune_x,type_x,date,type_energie,datetime_hour,temperature_c,humidite_pct,vitesse_vent_kmh,precipitation_mm,saison,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen,date_debut,date_fin,tarif_unitaire,cout_financier
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau,2023-01-01,6.4,88.7,3.9,0.0,Hiver,Ecole Marseille 29,ecole,Marseille,2022,2014,D,427,2023-01-01,2023-12-31,3.5,5.600
2,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Ecole Paris 3,ecole,Paris,1695,2014,D,219,2023-01-01,2023-12-31,3.5,4.935
4,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau,2023-01-01,15.8,41.2,33.8,0.0,Hiver,Mairie Nice 96,mairie,Nice,473,2015,D,56,2023-01-01,2023-12-31,3.5,0.840
6,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 36,mediatheque,Toulouse,1994,1975,G,118,2023-01-01,2023-12-31,3.5,42.490
8,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121,2023-01-01,2023-12-31,3.5,8.190
10,BAT0034,m3,2023,1,2023-01-01,2.57,0.22,5.03,24,Mediatheque Toulouse 34,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 34,mediatheque,Toulouse,757,2010,D,46,2023-01-01,2023-12-31,3.5,8.995
12,BAT0131,m3,2023,1,2023-01-01,1.73,0.17,3.20,24,Mediatheque Saint-Etienne 131,Saint-Etienne,mediatheque,2023-01-01,eau,2023-01-01,-0.5,90.7,19.7,0.0,Hiver,Mediatheque Saint-Etienne 131,mediatheque,Saint-Etienne,584,2018,C,74,2023-01-01,2023-12-31,3.5,6.055
14,BAT0018,m3,2023,1,2023-01-01,1.34,0.15,2.53,24,Ecole Lyon 18,Lyon,ecole,2023-01-01,eau,2023-01-01,10.7,72.1,14.8,0.0,Hiver,Ecole Lyon 18,ecole,Lyon,1664,1990,D,390,2023-01-01,2023-12-31,3.5,4.690
16,BAT0070,m3,2023,1,2023-01-01,1.31,0.13,2.74,24,Ecole Strasbourg 70,Strasbourg,ecole,2023-01-01,eau,2023-01-01,3.7,52.0,8.7,0.0,Hiver,Ecole Strasbourg 70,ecole,Strasbourg,814,1966,G,270,2023-01-01,2023-12-31,3.5,4.585
18,BAT0005,m3,2023,1,2023-01-01,305.53,31.07,608.21,23,Piscine Paris 5,Paris,piscine,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Piscine Paris 5,piscine,Paris,3913,1950,G,242,2023-01-01,2023-12-31,3.5,1069.355

---

## Creer des features derivees :
  - Consommation par occupant
  - Consommation par m2
  - Cout journalier, mensuel, annuel
  - Indice de performance energetique (IPE)
  - Ecart a la moyenne de la categorie

In [55]:
## Consommation par occupant
print("- Consommation par occupant :")
df_merge["conso_par_occupant"] = (
    df_merge["consommation_mean"] / df_merge["nb_occupants_moyen"]
).replace([float("inf"), -float("inf")], pd.NA)
df_merge.head()

- Consommation par occupant :

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,commune_x,type_x,date,type_energie,datetime_hour,temperature_c,humidite_pct,vitesse_vent_kmh,precipitation_mm,saison,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen,date_debut,date_fin,tarif_unitaire,cout_financier,conso_par_occupant
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau,2023-01-01,6.4,88.7,3.9,0.0,Hiver,Ecole Marseille 29,ecole,Marseille,2022,2014,D,427,2023-01-01,2023-12-31,3.5,5.600,0.003747
2,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Ecole Paris 3,ecole,Paris,1695,2014,D,219,2023-01-01,2023-12-31,3.5,4.935,0.006438
4,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau,2023-01-01,15.8,41.2,33.8,0.0,Hiver,Mairie Nice 96,mairie,Nice,473,2015,D,56,2023-01-01,2023-12-31,3.5,0.840,0.004286
6,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 36,mediatheque,Toulouse,1994,1975,G,118,2023-01-01,2023-12-31,3.5,42.490,0.102881
8,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121,2023-01-01,2023-12-31,3.5,8.190,0.019339

In [56]:
## Consommation par m²
df_merge["conso_par_m2"] = (
    df_merge["consommation_mean"] / df_merge["surface_m2"]
).replace([float("inf"), -float("inf")], pd.NA)

## Coûts temporels
    # Coût journalier
df_merge["cout_journalier"] = df_merge["cout_financier"]
    # Coût mensuel
df_cout_mensuel = (
    df_merge
    .groupby(
        ["batiment_id", "year", "month", "type_energie"],
        as_index=False
    )
    .agg(cout_mensuel=("cout_financier", "sum"))
)
    # Coût annuel
df_cout_annuel = (
    df_merge
    .groupby(
        ["batiment_id", "year", "type_energie"],
        as_index=False
    )
    .agg(cout_annuel=("cout_financier", "sum"))
)

    # Indice de Performance Énergétique (IPE) (IPE = consommation annuelle / surface (kWh/m²/an))
        # conso annuelle
df_conso_annuelle = (
    df_merge
    .groupby(
        ["batiment_id", "year", "type_energie"],
        as_index=False
    )
    .agg(conso_annuelle=("consommation_mean", "sum"))
)
        # Calcul de l’IPE
df_conso_annuelle = df_conso_annuelle.merge(
    df_merge[["batiment_id", "surface_m2"]].drop_duplicates(),
    on="batiment_id",
    how="left"
)

df_conso_annuelle["IPE_kwh_m2_an"] = (
    df_conso_annuelle["conso_annuelle"] / df_conso_annuelle["surface_m2"]
).round(2)

## Écart à la moyenne de la catégorie
    # Moyenne par catégorie
mean_by_category = (
    df_merge
    .groupby("type_y", as_index=False)
    .agg(conso_moyenne_categorie=("conso_par_m2", "mean"))
)
    # Écart absolu et relatif
df_merge = df_merge.merge(
    mean_by_category,
    on="type_y",
    how="left"
)

df_merge["ecart_moyenne_categorie"] = (
    df_merge["conso_par_m2"] - df_merge["conso_moyenne_categorie"]
)

df_merge["ecart_moyenne_categorie_pct"] = (
    df_merge["ecart_moyenne_categorie"] / df_merge["conso_moyenne_categorie"]
).round(2)

df_merge.head()

,batiment_id,unite,year,month,timestamp_start,consommation_mean,consommation_min,consommation_max,measurement_count,nom_x,commune_x,type_x,date,type_energie,datetime_hour,temperature_c,humidite_pct,vitesse_vent_kmh,precipitation_mm,saison,nom_y,type_y,commune_y,surface_m2,annee_construction,classe_energetique,nb_occupants_moyen,date_debut,date_fin,tarif_unitaire,cout_financier,conso_par_occupant,conso_par_m2,cout_journalier,conso_moyenne_categorie,ecart_moyenne_categorie,ecart_moyenne_categorie_pct
0,BAT0029,m3,2023,1,2023-01-01,1.60,0.14,3.38,24,Ecole Marseille 29,Marseille,ecole,2023-01-01,eau,2023-01-01,6.4,88.7,3.9,0.0,Hiver,Ecole Marseille 29,ecole,Marseille,2022,2014,D,427,2023-01-01,2023-12-31,3.5,5.600,0.003747,0.000791,5.600,0.070816,-0.070025,-0.99
1,BAT0003,m3,2023,1,2023-01-01,1.41,0.13,2.74,24,Ecole Paris 3,Paris,ecole,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Ecole Paris 3,ecole,Paris,1695,2014,D,219,2023-01-01,2023-12-31,3.5,4.935,0.006438,0.000832,4.935,0.070816,-0.069984,-0.99
2,BAT0096,m3,2023,1,2023-01-01,0.24,0.02,0.46,24,Mairie Nice 96,Nice,mairie,2023-01-01,eau,2023-01-01,15.8,41.2,33.8,0.0,Hiver,Mairie Nice 96,mairie,Nice,473,2015,D,56,2023-01-01,2023-12-31,3.5,0.840,0.004286,0.000507,0.840,0.054514,-0.054007,-0.99
3,BAT0036,m3,2023,1,2023-01-01,12.14,1.41,26.12,24,Mediatheque Toulouse 36,Toulouse,mediatheque,2023-01-01,eau,2023-01-01,4.6,37.5,12.6,12.6,Hiver,Mediatheque Toulouse 36,mediatheque,Toulouse,1994,1975,G,118,2023-01-01,2023-12-31,3.5,42.490,0.102881,0.006088,42.490,0.075807,-0.069718,-0.92
4,BAT0004,m3,2023,1,2023-01-01,2.34,0.23,5.29,23,Mediatheque Paris 4,Paris,mediatheque,2023-01-01,eau,2023-01-01,2.5,31.8,11.0,6.9,Hiver,Mediatheque Paris 4,mediatheque,Paris,907,2019,C,121,2023-01-01,2023-12-31,3.5,8.190,0.019339,0.002580,8.190,0.075807,-0.073227,-0.97

---

## Creation de consommations_enrichies.csv & consommations_enrichies.parquet

In [57]:
csv_consommations_enrichies_path = os.path.join(OUTPUT_DIR,"consommations_enrichies.csv")
parquet_consommations_enrichies_path = os.path.join(OUTPUT_DIR,"consommations_enrichies.parquet")

## Écriture en CSV
df_merge.to_csv(csv_consommations_enrichies_path, index=False)

## Écriture en Parquet
df_merge.to_parquet(
    parquet_consommations_enrichies_path,
    engine="pyarrow",
    index=False
)